---
- name: Install VSCode extensions
  include_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    user:
      - username: "{{ archlinux_username }}"
        visual_studio_code_extensions:
          - vscodevim.vim
          - vscode-icons-team.vscode-icons
          - editorconfig.editorconfig
          - mechatroner.rainbow-csv
          - espenb.prettier-vscode
          - hbenl.vscode-text-explorer
