---
- name: Install VSCode extensions
  include_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ archlinux_username }}"
        visual_studio_code_extensions:
          - vscodevim.vim
          - vscode-icons-team.vscode-icons
          - editorconfig.editorconfig
          - mechatroner.rainbow-csv
          - esbenp.prettier-vscode
          - hbenl.vscode-text-explorer
          - ms-dotnettools.csharp
          - jchannon.csharpextensions
          - rtbenfield.vscode-jest-test-adapter
          - rust-lang.rust
          - arjun.swagger-viewer
          - randomchance.logstash
          - ms-vscode.azure-account
          - summer.azure-event-hub-explorer
          - ms-azuretools.vscode-azurefunctions
          - ms-azure-devops.azure-pipelines
