---
- name: Check that bugged screen sharing overlay exists
  stat:
    path: /usr/share/teams/resources/app.asar.unpacked/node_modules/slimcore/bin/rect-overlay
  register: overlay

- name: Fix screen sharing bug in teams when using i3
  command: mv "{{ overlay.stat.path }}" "{{ item.stat.path }}.bak"
  when: overlay.stat.exists == true
