---
# Remove informant (will break automatic pacman if installed)
- import_tasks: user/remove-informant.yml

# Install bare necessities
- import_tasks: core/pacman.yml
- import_tasks: core/firmware.yml
- import_tasks: core/network.yml

# Setup system
- import_tasks: system/cpu.yml
- import_tasks: system/gpu.yml
- import_tasks: system/filesystem.yml
- import_tasks: system/zsh.yml
- import_tasks: system/automount.yml

# Set the clock and locale
- import_tasks: locale/time.yml
- import_tasks: locale/locale.yml

# Set up aur user
- import_tasks: aur-setup/create-aur-user.yml

# Configure a user
- import_tasks: user/user.yml
- import_tasks: user/openssh.yml
- import_tasks: user/zsh-user-setup.yml
- import_tasks: user/manpages.yml
- import_tasks: user/git.yml
- import_tasks: user/backup.yml

# Install the desktop
- import_tasks: desktop/keyring.yml
- import_tasks: desktop/vim.yml
- import_tasks: desktop/gui.yml
- import_tasks: desktop/xorg.yml
- import_tasks: desktop/audio.yml
- import_tasks: desktop/i3.yml
- import_tasks: desktop/rofi.yml
- import_tasks: desktop/notifications.yml
- import_tasks: desktop/picom.yml
- import_tasks: desktop/polybar.yml
- import_tasks: desktop/wallpaper.yml
- import_tasks: desktop/terminal.yml
- import_tasks: desktop/applications.yml

# Install some programming languages
- import_tasks: development/general.yml
- import_tasks: development/python.yml
- import_tasks: development/node.yml
- import_tasks: development/dotnet.yml
- import_tasks: development/rust.yml

# Install work-specific stuff
- import_tasks: work/azure.yml
- import_tasks: work/applications.yml
- import_tasks: work/vpn.yml

# Set up login manager
- import_tasks: login-manager/lxdm.yml

# Install informant (will break automatic pacman if installed earlier)
- import_tasks: user/add-informant.yml

# Cleanup
- import_tasks: aur-setup/remove-aur-user.yml
