- name: install gaming packages
  become: true
  pacman:
    name:
      - cachyos-gaming-applications # meta package

- name: install applications
  become: true
  pacman:
    name:
      - ranger
      - yay
      - spotify-launcher
      - vivaldi
      - ttf-fira-code
      - code

- name: install from aur
  kewlfft.aur.aur:
    name:
      - jotta-cli
    state: present
  become: yes
  become_user: aur_builder

- import_tasks: ranger.yml
- import_tasks: vim.yml
- import_tasks: vscode.yml
- import_tasks: git.yml
- import_tasks: steam.yml