for file in "$HOME/.config/zsh.d"/*; do
    source "$file"
done

for file in "$HOME/.config/zsh_completion.d"/*; do
    source "$file"
done

# Make 'nvm'-command available. Must be sourced last ...
source /usr/share/nvm/init-nvm.sh