---
- name: install work applications from aur
  kewlfft.aur.aur:
    name:
      - postman-bin
      - jetbrains-toolbox
      - slack-desktop
      - teams
    state: present
  become: true
  become_user: aur_builder

- name: configure rider vim plugin
  copy:
    src: vim/ideavimrc
    dest: /home/{{ archlinux_username }}/.ideavimrc
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

# Ref: https://docs.microsoft.com/en-us/answers/questions/42095/sharing-screen-not-working-anymore-bug.html
- name: Check that bugged screen sharing overlay exists
  stat:
    path: /usr/share/teams/resources/app.asar.unpacked/node_modules/slimcore/bin/rect-overlay
  register: overlay

- name: Fix screen sharing bug in teams when using i3
  command: mv "{{ overlay.stat.path }}" "{{ overlay.stat.path }}.bak"
  when: overlay.stat.exists == true

- name: Install work VSCode extensions
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ archlinux_username }}"
        visual_studio_code_extensions:
          - arjun.swagger-viewer
          - randomchance.logstash
