---
- name: install work applications
  aur:
    name:
      - postman-bin
      - jetbrains-toolbox
    state: present
  become: true
  become_user: aur_builder

- name: configure rider vim plugin
  copy:
    src: vim/ideavimrc
    dest: /home/{{ archlinux_username }}/.ideavimrc
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"
