---
- name: install azure tools (AUR)
  kewlfft.aur.aur:
    name:
      - azure-functions-core-tools-bin
      - azure-cli
    state: present
  become: true
  become_user: aur_builder

- name: Install Microsoft Credential Provider
  shell:
    cmd: "wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash"
    warn: false
  become: yes
  become_user: "{{ archlinux_username }}"

- name: Readd rsa support to openssh
  blockinfile:
    path: "/home/{{ archlinux_username }}/.ssh/config"
    block: |
      # Workaround for Azure DevOps, which ONLY supports rsa. This is not safe
      PubkeyAcceptedKeyTypes +ssh-rsa
    marker: "# {mark} Config for using SSH with Azure DevOps"
  become: yes
  become_user: "{{ archlinux_username }}"

- name: Install Azure VSCode extensions
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ archlinux_username }}"
        visual_studio_code_extensions:
          - ms-vscode.azure-account
          - summer.azure-event-hub-explorer
          - ms-azuretools.vscode-azurefunctions
          - ms-azure-devops.azure-pipelines


- name: copy az cli autocompletion file
  copy:
    src: "zsh_completion.d/az.completion"
    dest: /home/{{ archlinux_username}}/.config/zsh_completion.d/az.completion"
    owner: "{{ archlinux_username }}"
    group: users
  become: true