---
- name: create alacritty configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/alacritty
    state: directory
    owner: "{{ ansible_user_id }}"
    group: users

- name: configure alacritty
  copy:
    src: alacritty/alacritty.yml
    dest: /home/{{ ansible_user_id }}/.config/alacritty/alacritty.yml
    owner: "{{ ansible_user_id }}"
    group: users