---
- name: create bashmarks configuration directory
  file:
    name: /home/{{ansible_user_id}}/.config/bashmarks
    state: directory

- name: create bashmarks script
  copy:
    src: bashmarks/bashmarks.sh
    dest: /home/{{ansible_user_id}}/.config/bashmarks/bashmarks.sh

- name: configure bashmarks
  template:
    src: shell/20-bashmarks
    dest: /home/{{ansible_user_id}}/.config/zsh.d/
