---
- name: copy i3 configuration files
  copy:
    src: "i3/conf.d/{{item}}"
    dest: /home/{{ ansible_user_id }}/.config/i3/conf.d/{{item}}
    owner: "{{ ansible_user_id }}"
    group: users
  with_items:
    - 10-audio-keys.conf
    - 10-autostart.conf
    - 10-keyboardlayout.conf
    - 10-lockscreen.conf
    - 10-visuals.conf
    - 20-screenshot.conf
    - 50-floating-overrides.conf