---
- name: create rofi configuration directory
  file:
    name: /home/{{ansible_user_id}}/.config/rofi
    state: directory

- name: create rofi custom scripts
  copy:
    src: "rofi/{{item}}"
    dest: /home/{{ ansible_user_id }}/.config/rofi/{{item}}
    owner: "{{ ansible_user_id }}"
    group: users
    mode: 0755
  with_items:
    - monitor_layout.sh

- name: Add rofi launch keybindings to i3
  blockinfile:
    path: "/home/{{ ansible_user_id }}/.config/i3/config"
    block: |
      bindsym $mod+m exec ~/.config/rofi/monitor_layout.sh
    marker: "# {mark} Rofi launcher bindings"