---
- name: create rofi configuration directory
  file:
    name: /home/{{ansible_user_id}}/.config/rofi
    state: directory

- name: create rofi custom scripts
  copy:
    src: "rofi/{{item}}"
    dest: /home/{{ ansible_user_id }}/.config/rofi/{{item}}
    owner: "{{ ansible_user_id }}"
    group: users
    mode: 0755
  with_items:
    - monitor_layout.sh
    - screenlayout.py
    - config.rasi
    - customtheme.rasi

- name: Add rofi launch keybindings to i3
  copy:
    src: "rofi/30-rofi.conf"
    dest: /home/{{ ansible_user_id }}/.config/i3/conf.d/30-rofi.conf
    owner: "{{ ansible_user_id }}"
    group: users