---

- name: configure .vimrc
  copy:
    src: vim/vimrc
    dest: /home/{{ ansible_user_id }}/.vimrc
    owner: "{{ ansible_user_id }}"
    group: users

- name: Create autoload directory
  file:
    name: /home/{{ ansible_user_id }}/.vim/autoload
    state: directory
    owner: "{{ ansible_user_id }}"
    group: users

- name: Download vim plugged
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ ansible_user_id }}/.vim/autoload/plug.vim
    owner: "{{ ansible_user_id }}"
    group: users

- name: Install plugins
  shell: vim -E -s -c "source /home/{{ ansible_user_id }}/.vimrc" +PlugInstall -c qa

- name: configure rider vim plugin
  copy:
    src: vim/ideavimrc
    dest: /home/{{ ansible_user_id }}/.ideavimrc
    owner: "{{ ansible_user_id }}"
    group: users