- name: install nvm
  kewlfft.aur.aur:
    name:
      - nvm
    state: present
  become: yes
  become_user: aur_builder

- name: Install node and set version
  shell: "source /usr/share/nvm/init-nvm.sh && nvm install {{ archlinux_node_version }} && nvm alias default {{ archlinux_node_version }}"

- name: Add needed NVM-settings to .zshrc
  blockinfile:
    path: "/home/{{ ansible_facts['user_id'] }}/.zshrc"
    block: |
      # Make 'nvm'-command available. Must be sourced last ...
      NVM_SYMLINK_CURRENT=true
      source /usr/share/nvm/init-nvm.sh
    marker: "# {mark} NVM setup"

- name: copy zshenv file
  copy:
    src: "node/50-node"
    dest: /home/{{ ansible_facts['user_id']}}/.config/zshenv.d/50-node