---
- name: install rust
  pacman:
    name: rustup
  become: true

- name: Install rust VSCode extensions
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions:
          - rust-lang.rust-analyzer
