---
- name: install work applications from aur
  kewlfft.aur.aur:
    name:
      - bruno-bin
      - slack-desktop
    state: present

- name: install kubectl and kustomize
  pacman:
    name:
      - kubectl
      - kustomize
      - kubectx
  become: true

- name: install azure tools (AUR)
  kewlfft.aur.aur:
    name:
      - azure-cli
    state: present
  become: yes
  become_user: aur_builder

- name: copy az cli autocompletion file
  copy:
    src: "azure/az.completion"
    dest: /home/{{ ansible_facts['user_id'] }}/.config/zsh_completion.d/az.completion"