---
- name: install utilities
  pacman:
    name:
      - curl
      - jq
      - less
      - which
      - xclip
      - scrot
  become: true

- name: install applications
  pacman:
    name:
      - firefox
      - firefox-developer-edition
      - keepassxc
      - thunderbird
      - steam
      - ranger
      - nemo
  become: true

- name: create ranger configuration directory
  file:
    name: /home/{{ archlinux_username }}/.config/ranger
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: copy ranger configuration
  copy:
    src: ranger/rc.conf
    dest: /home/{{ archlinux_username }}/.config/ranger/rc.conf
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

# this does not work
- name: import gpg keys for AUR packages
  become: yes
  become_user: "{{ archlinux_username }}"
  shell:
    cmd: curl {{ item }} | gpg --import -
    warn: false
  with_items:
    - https://download.spotify.com/debian/pubkey.gpg

- name: import gpg keys for AUR packages for build user
  become: yes
  become_user: aur_builder
  shell:
    cmd: curl {{ item }} | gpg --import -
    warn: false
  with_items:
    - https://download.spotify.com/debian/pubkey.gpg
#

- name: install from aur
  kewlfft.aur.aur:
    name:
      - visual-studio-code-bin
      - yay
      - spotify
      - jotta-cli
    state: present
  become: true
  become_user: aur_builder

- name: Add spotify keybindings
  blockinfile:
    path: "/home/{{ archlinux_username }}/.config/i3/config"
    block: |
      bindsym XF86AudioPlay exec --no-startup-id dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
      bindsym XF86AudioNext exec --no-startup-id dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
      bindsym XF86AudioPrev exec --no-startup-id dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
      bindsym XF86AudioStop exec --no-startup-id dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
    marker: "# {mark} Media keys specific to spotify"
  become: yes
  become_user: "{{ archlinux_username }}"

- name: Install VSCode extensions
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ archlinux_username }}"
        visual_studio_code_extensions:
          - vscodevim.vim
          - vscode-icons-team.vscode-icons
          - editorconfig.editorconfig
          - mechatroner.rainbow-csv
          - esbenp.prettier-vscode
          - hbenl.vscode-test-explorer
