---
- name: install utilities
  pacman:
    name:
      - curl
      - jq
      - less
      - which
      - xclip
      - flameshot
  become: true

- name: install applications
  pacman:
    name:
      - firefox
      - bitwarden
      - spotify-launcher
      - steam
      - ranger
      - lib32-libsm # Needed by Guitar pro
      - lib32-pipewire-jack # Needed by Guitar pro
  become: true

- name: install from aur
  kewlfft.aur.aur:
    name:
      - yay
      - jotta-cli
      - guitar-pro
    state: present
