---
- name: install audio tools
  pacman:
    name:
      - alsa-firmware
      - alsa-utils
      - pavucontrol
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - helvum
      - easyeffects
  become: true
