- name: install nemo and ranger
  pacman:
    name:
      - nemo
      - ranger
  become: true

- name: Set terminal in nemo
  dconf:
    key: "/org/cinnamon/desktop/applications/terminal/exec"
    value: "'alacritty'"
    state: present

- name: Set terminal args in nemo
  dconf:
    key: "/org/cinnamon/desktop/applications/terminal/exec-arg"
    value: "'-e'"
    state: present

- name: create ranger configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/ranger
    state: directory

- name: copy ranger configuration
  copy:
    src: ranger/rc.conf
    dest: /home/{{ ansible_user_id }}/.config/ranger/rc.conf
