---
- name: install i3
  pacman:
    name:
      - i3-wm
      - i3lock
  become: true

- name: create i3 configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/i3
    state: directory

- name: create i3 conf.d directory
  file:
    name: /home/{{ ansible_user_id }}/.config/i3/conf.d
    state: directory

- name: configure i3
  copy:
    src: i3/config
    dest: /home/{{ ansible_user_id }}/.config/i3/config

- name: copy i3 configuration files
  copy:
    src: "i3/conf.d/{{item}}"
    dest: /home/{{ ansible_user_id}}/.config/i3/conf.d/{{item}}
  with_items:
    - 10-base.conf
    - 10-movement.conf
    - 10-audio-keys.conf
    - 10-autostart.conf
    - 10-keyboardlayout.conf
    - 10-lockscreen.conf
    - 10-visuals.conf
    - 20-screenshot.conf
    - 50-floating-overrides.conf

- name: install i3-quickterm deps
  pacman:
    name:
      - python
      - python-pip
  become: true

- name: install i3 quickterm
  pip:
    name: i3-quickterm

- name: configure i3 quickterm
  copy:
    src: i3/i3-quickterm.json
    dest: /home/{{ ansible_user_id }}/.config/i3/i3-quickterm.json
