---
- name: install notification libs
  pacman:
    name:
      - libnotify
      - dunst
  become: true

- name: create dunst configuration directory
  file:
    name: /home/{{ archlinux_username }}/.config/dunst
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: configure dunst
  copy:
    src: dunstrc
    dest: /home/{{ archlinux_username }}/.config/dunst/dunstrc
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: Start dunst on login
  blockinfile:
    path: "/home/{{ archlinux_username }}/.config/i3/config"
    block: |
      exec --no-startup-id /usr/bin/dunst
    marker: "# {mark} Notification daemon"
  become: yes
  become_user: "{{ archlinux_username }}"
