---
- name: install notification libs
  pacman:
    name:
      - libnotify
      - dunst
  become: true

- name: create dunst configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/dunst
    state: directory

- name: configure dunst
  copy:
    src: dunstrc
    dest: /home/{{ ansible_user_id }}/.config/dunst/dunstrc
