---
- name: install picom
  pacman:
    name: picom
  become: true

- name: create picom configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/picom
    state: directory

- name: configure picom
  copy:
    src: picom.conf
    dest: /home/{{ ansible_user_id }}/.config/picom/picom.conf
