- name: install polybar
  pacman:
    name: polybar
    state: present
  become: true

- name: create polybar configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/polybar
    state: directory

- name: copy polybar configuration files
  copy:
    src: "polybar/{{item}}"
    dest: /home/{{ ansible_user_id}}/.config/polybar/{{item}}
    mode: 0755
  with_items:
    - config
    - inputlang.sh
    - launch.sh
    - spotify.sh

- name: copy bluetooth polybar scripts
  when: bluetooth.rc == 0
  copy:
    src: "bluetooth/{{item}}"
    dest: /home/{{ ansible_user_id}}/.config/polybar/{{item}}
    mode: 0755
  with_items:
    - bluetooth.sh
    - toggle_bluetooth.sh
