---
- name: install alacritty
  pacman:
    name: alacritty
  become: true

- name: create alacritty configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/alacritty
    state: directory

- name: configure alacritty
  copy:
    src: alacritty/alacritty.yml
    dest: /home/{{ ansible_user_id }}/.config/alacritty/alacritty.yml
