---
- name: install termite
  pacman:
    name: termite
  become: true

- name: create termite configuration directory
  file:
    name: /home/{{ archlinux_username }}/.config/termite
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: configure termite
  copy:
    src: termite/config
    dest: /home/{{ archlinux_username }}/.config/termite/config
    owner: "{{ archlinux_username }}"
    group: users
  become: true
