---
- name: install vim
  pacman:
    name: gvim # To get vim where clipboard is enabled
  become: true

- name: configure .vimrc
  copy:
    src: vim/vimrc
    dest: /home/{{ ansible_user_id }}/.vimrc
  register: vimconfig

- name: Create autoload directory
  file:
    name: /home/{{ ansible_user_id }}/.vim/autoload
    state: directory

- name: Download vim plugged
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ ansible_user_id }}/.vim/autoload/plug.vim

- name: Install plugins
  shell: vim -E -s -c "source /home/{{ ansible_user_id }}/.vimrc" +PlugInstall -c qa
  changed_when: vimconfig.changed
