---
- name: install networking tools
  pacman:
    name:
      - iwd
      - systemd-resolvconf
  become: true

- name: configure iwd
  copy:
    src: iwd/main.conf
    dest: /etc/iwd/main.conf
    owner: root
    group: root
  become: true

- name: create systemd override directory for iwd
  file:
    name: /etc/systemd/system/iwd.service.d
    state: directory
    owner: root
    group: root
  become: true

- name: add override unit file for iwd
  copy:
    src: iwd/systemd-unit.override.conf
    dest: /etc/systemd/system/iwd.service.d/override.conf
    owner: root
    group: root
  become: true

- name: Create symbolic link for systemd resolv.conf
  file:
    src: "/run/systemd/resolve/resolv.conf"
    dest: "/etc/resolv.conf"
    state: link
    force: true

- name: start iwd daemon
  systemd:
    state: started
    name: iwd
    enabled: true
  become: yes

- name: start networkd daemon
  systemd:
    state: started
    name: systemd-networkd
    enabled: true
  become: yes

- name: start resolve daemon
  systemd:
    state: started
    name: systemd-resolved
    enabled: true
  become: yes

- name: Set hostname
  hostname:
    name: "{{ archlinux_hostname }}"

- name: configure hosts file
  template:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
