---
- name: detect bluetooth device
  shell: lsusb | grep -i bluetooth
  register: bluetooth
  ignore_errors: true
  changed_when: false

- name: install bluetooth packages
  when: bluetooth.rc == 0
  pacman:
    name:
      - bluez
      - bluez-utils
      - blueberry
  become: true
