- name: install nfs-utils
  pacman:
    name: nfs-utils
  become: true

- name: create mount directory
  file:
    name: /mnt/media
    state: directory
    owner: root
    group: 100
    mode: "2777"
  become: true

- name: Add nfs server to fstab
  blockinfile:
    path: "/etc/fstab"
    block: |
      192.168.50.225:/export/media    /mnt/media  nfs noauto,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14,x-systemd.idle-timeout=1min  0 0
    marker: "# {mark} Local NFS Server"
  become: true
