---
- name: Install zsh
  pacman:
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
  become: true

- name: Clone oh-my-zsh repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh

- name: create zsh configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/zsh.d
    state: directory

- name: create zsh env configuration directory
  file:
    name: /home/{{ ansible_user_id }}/.config/zshenv.d
    state: directory

- name: create zsh completion directory
  file:
    name: /home/{{ ansible_user_id }}/.config/zsh_completion.d
    state: directory

- name: copy zshrc files
  copy:
    src: "zsh.d/{{item}}"
    dest: /home/{{ansible_user_id}}/.config/zsh.d/{{item}}
  with_items:
    - 10-oh-my-zsh
    - 10-aliases
    - 10-completion
    - 10-history
    - 10-utility-functions
    - 10-vim
    - 10-fishlike

- name: copy zshenv files
  copy:
    src: "zshenv.d/{{item}}"
    dest: /home/{{ansible_user_id}}/.config/zshenv.d/{{item}}
  with_items:
    - 10-qt
    - 10-base
    - 10-xdg
    - 10-firefox
    - 10-vi-mode

- name: Add dummy file to completion directory
  copy:
    content: ""
    dest: "/home/{{ ansible_user_id }}/.config/zsh_completion.d/dummy"
    force: false
