---
- name: install lxdm
  pacman:
    name: lxdm-gtk3
  become: true

- name: create lxdm configuration directory
  file:
    name: /etc/lxdm
    state: directory
    owner: root
    group: root
  become: true

- name: configure lxdm
  template:
    src: lxdm.conf
    dest: /etc/lxdm/lxdm.conf
    owner: root
    group: root
  become: true

- name: add postlogin script
  copy:
    src: lxdm/PostLogin
    dest: /etc/lxdm/PostLogin
    owner: root
    group: root
    mode: 0755
  become: true

- name: start lxdm service
  systemd:
    name: lxdm
    enabled: true
  become: yes
