---
- name: install lightdm
  pacman:
    name: 
    - lightdm
    - light-locker
  become: true

- name: install aether theme
  kewlfft.aur.aur:
    name:
      - lightdm-webkit-theme-aether
    state: present
  become: true
  become_user: aur_builder

- name: create lightdm configuration directory
  file:
    name: /etc/lightdm/lightdm.conf.d
    state: directory
    owner: root
    group: root
  become: true

- name: configure lightdm
  copy:
    src: lightdm/10-default-settings.conf
    dest: /etc/lightdm/lightdm.conf.d/10-default-settings.conf
    owner: root
    group: root
  become: true

- name: start lightdm service
  systemd:
    name: lightdm
    enabled: true
  become: true
