call plug#begin('~/.vim/plugged')

Plug 'zacanger/angr.vim'
Plug 'bronson/vim-trailing-whitespace'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'

call plug#end()

" :PlugInstall to install new plugins

" Theme
set background=dark
try
	colorscheme angr
catch
endtry

if (exists('+colorcolumn'))
	set colorcolumn=80
	highlight ColorColumn ctermbg=1
endif


" Enable Vim features
set nocompatible
set enc=utf-8
syntax on
set hlsearch
set nowrap
set relativenumber

" Tab management
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent