---
- name: install dotnet core
  pacman:
    name:
      - dotnet-sdk
      - dotnet-runtime
      - aspnet-runtime
  become: true

- name: copy zshenv file
  copy:
    src: "zshenv.d/50-dotnet"
    dest: /home/{{ archlinux_username}}/.config/zshenv.d/50-dotnet
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

- name: install jetbrains toolbox
  aur:
    name:
      - jetbrains-toolbox
    state: present
  become: true
  become_user: aur_builder

- name: Install dotnet VSCode extensions
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ archlinux_username }}"
        visual_studio_code_extensions:
          - ms-dotnettools.csharp
          - jchannon.csharpextensions
