---
- name: install docker
  pacman:
    name: docker
  become: true

- name: add user to docker group
  user:
    name: "{{ archlinux_username }}"
    groups:
      - docker
    append: true
  become: true

- name: mask systemd-networkd-wait-online to stop docker from being blocked on startup
  systemd:
    name: systemd-networkd-wait-online.service
    enabled: no
    masked: yes
  become: yes
