---
- name: install python development tools
  pacman:
    name:
      - python
      - python-pip
      - python-virtualenv
  become: true

- name: copy zshenv file
  copy:
    src: "zshenv.d/50-python"
    dest: /home/{{ archlinux_username}}/.config/zshenv.d/50-python
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"
