---
- name: install rust
  pacman:
    name: rust
  become: true

- name: Install rust VSCode extensions
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ archlinux_username }}"
        visual_studio_code_extensions:
          - rust-lang.rust
