---
- name: install informant
  kewlfft.aur.aur:
    name: informant
    state: present
  become: true
  become_user: aur_builder
  changed_when: false

- name: add user to informant group
  user:
    name: "{{ archlinux_username }}"
    groups:
      - informant
    append: true
  become: true
