---
- name: install informant
  kewlfft.aur.aur:
    name: informant
    state: present
  changed_when: false

- name: add user to informant group
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - informant
    append: true
  become: true
