---
- name: install snapper
  pacman:
    name:
      - cronie
      - snapper
  become: true

# TODO Configure snapper

- name: start cronie service
  systemd:
    name: cronie
    enabled: true
  become: true
