---
- name: install snapper and tools
  pacman:
    name:
      - cronie
      - snapper
      - snap-pac
  become: true

- name: start cronie service
  systemd:
    name: cronie
    enabled: true
  become: true
