---
- name: install timeshift
  kewlfft.aur.aur:
    name: timeshift
    state: present
  become: true
  become_user: aur_builder
  changed_when: false

- name: start cronie service
  systemd:
    name: cronie
    enabled: true
  become: yes