---
- name: install informant
  kewlfft.aur.aur:
    name: informant
    state: present

- name: add user to informant group
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - informant
    append: true
  become: true

- name: Enable informant
  file:
    path: "/etc/pacman.d/hooks/00-informant.hook"
    state: absent
  become: true
  changed_when: false
