---
- name: install git
  pacman:
    name:
      - git
      - git-lfs
  become: true

- name: create git configuration directory
  file:
    name: /home/{{ansible_user_id}}/.config/git
    state: directory

- name: configure git extension
  template:
    src: shell/20-git-ext
    dest: /home/{{ansible_user_id}}/.config/zsh.d/

- name: create git ext script
  copy:
    src: git/git-ext
    dest: /home/{{ansible_user_id}}/.config/git/git-ext
    mode: "u=rwx"

- name: copy git config
  copy:
    src: git/gitconfig
    dest: /home/{{ ansible_user_id }}/.config/git/gitconfig

- name: reference config from main gitconfig
  blockinfile:
    path: "/home/{{ ansible_user_id }}/.gitconfig"
    create: true
    block: |
      [include]
          path = .config/git/gitconfig
    marker: "# {mark} Default git configuration"
