---
- name: install git
  pacman:
    name:
      - git
      - git-lfs
  become: true

- name: create git configuration directory
  file:
    name: /home/{{ansible_user_id}}/.config/git
    state: directory

- name: configure git extension
  template:
    src: shell/20-git-ext
    dest: /home/{{ansible_user_id}}/.config/zsh.d/

- name: create git ext script
  copy:
    src: git/git-ext
    dest: /home/{{ansible_user_id}}/.config/git/git-ext
    mode: "u=rwx"
