---
- name: install git
  pacman:
    name: git
  become: true

- name: create git configuration directory
  file:
    name: /home/{{archlinux_username}}/.config/git
    state: directory

- name: configure git extension
  template:
    src: shell/20-git-ext
    dest: /home/{{archlinux_username}}/.config/zsh.d/

- name: create git ext script
  copy:
    src: git/git-ext
    dest: /home/{{archlinux_username}}/.config/git/git-ext
    mode: "u=rwx"
