---
- name: create openssh client configuration directory
  file:
    dest: /home/{{ ansible_user_id }}/.ssh
    state: directory
  become: true

- name: configure openssh client
  copy:
    src: openssh/ssh_config
    dest: /home/{{ ansible_user_id }}/.ssh/config
    mode: 0644
