---
- name: create openssh client configuration directory
  file:
    dest: /home/{{ ansible_user_id }}/.ssh
    state: directory

- name: configure openssh client
  copy:
    src: openssh/ssh_config
    dest: /home/{{ ansible_user_id }}/.ssh/config
    mode: 0644

- name: generate default SSH key
  openssh_keypair:
    path: "/home/{{ ansible_user_id }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
