---
- name: install syncthing 
  pacman:
    name:
      - syncthing
  become: true

- name: start syncthing service
  systemd:
    name: syncthing
    enabled: true
    scope: user
  become: yes
  become_user: "{{ archlinux_username }}"