---
- name: create normal user
  user:
    name: "{{ ansible_user_id }}"
    group: users
    home: /home/{{ ansible_user_id }}
    groups:
      - wheel
    shell: /bin/zsh
  become: true

- name: create home directory
  file:
    name: /home/{{ ansible_user_id }}
    state: directory
    owner: "{{ ansible_user_id }}"
    group: users
  become: true

- name: create scripts directory
  file:
    name: /home/{{ ansible_user_id }}/bin
    state: directory

- name: create config directory
  file:
    name: /home/{{ ansible_user_id }}/.config
    state: directory

- name: copy dotfiles
  copy:
    src: "{{item}}"
    dest: /home/{{ ansible_user_id}}/.{{item}}
  with_items:
    - zshenv
    - zshrc
    - zprofile
    - dmrc

- name: do not require pwd to shutdown via cli
  lineinfile:
    path: /etc/sudoers.d/12-no-pwd-for-power
    line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: /usr/bin/systemctl poweroff,/usr/bin/systemctl reboot"
    create: yes
    validate: "visudo -cf %s"
  become: true
