---
- name: Create AUR user
  user:
    name: aur_builder
    groups: wheel
  become: true

- name: Add user to sudoers
  lineinfile:
    path: /etc/sudoers.d/11-install-aur-builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
